baseurl         = ""
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Luiz Peixoto"
  subtitle    = "Direito com Privacidade"

  cover       = "bookcase.jpg"
  description = "Ferramentas para Iniciar o Trabalho"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "@adv_luizpeixoto"
  fbName = "luizpeixoto.adv"
  githubName = "eueung"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Luiz Peixoto"
  authorAvatar = "profile.jpeg"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Iniciar"
  url = "/tags/iniciar"
  weight = 100

[[menu.main]]
  name = "Consulta"
  url = "/categories/consulta/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95